# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_id', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=99)),
                ('party', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('top_cosponsor_subjects', models.CharField(max_length=500)),
                ('top_sponsor_subjects', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=50)),
                ('chamber', models.CharField(max_length=50)),
            ],
        ),
    ]
